apiVersion: apps/v1
kind: Deployment
metadata:
  name: jc-comms-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jc-comms-server
  template:
    metadata:
      labels:
        app: jc-comms-server
    spec:
      containers:
        - name: jc-comms-server
          image: milanspiridonov/jc-comms-server:production-latest # Use the Docker image we built earlier
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: jc-comms-server
spec:
  selector:
    app: jc-comms-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
  
