name: Workflow (Testing)

on:
  push:
    branches:
      - 'testing'

jobs:
  build_and_push_docker:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: milanspiridonov/jc-comms-server:testing-latest
  redeploy:
    runs-on: self-hosted
    needs: build_and_push_docker
    steps:
    - uses: actions/checkout@v4
    - run: kubectl apply -f dev.deployment.yaml
